server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: aviones-route
          uri: http://aviones-api:8000
          predicates:
            - Path=/ServiceAvion/**
          filters:
            - name: RewritePath
              args:
                regexp: "/ServiceAvion/(?<remaining>.*)"
                replacement: "/${remaining}"

        - id: agente-ia-route
          uri: http://api-mcp:5000
          predicates:
            - Path=/AgentIA/**
          filters:
            - name: RewritePath
              args:
                regexp: "/AgentIA/(?<remaining>.*)"
                replacement: "/${remaining}"
